### ISSUE TITLE
遇到一个php_screw的变形函数交流分析

### ISSUE THREAD

**Issue by Truelovefortony** [Skactor/php_screw-decrypt#1]
Hi,
       从你的Blog上看到关于php_screw的分析学习到了不少知识，现在就遇到一个类似PHP_screw函数的变形，似乎不是用pm9screw_mycryptkey[]进行加密了，因此找不到加密的数组。
原加密用的是：
newdatap[i] = (char)pm9screw_mycryptkey[(newdatalen - i) % cryptkey_len] ^ (~(newdatap[i]));
变形后的加密推测是：
newdatap[i] = (char)newdatap[i]-7-i;

zdecode函数也巧妙的换成了zlib库里的uncompress，可能学疏才浅，奈何一只分析不完整，解不出，如果可以交流一下吗？
提供so文件https://raw.githubusercontent.com/Truelovefortony/php_screw-decrypt/master/screw.so
一个已经被加密过的php文件https://raw.githubusercontent.com/Truelovefortony/php_screw-decrypt/master/test2.php

**Comment by Slzdude** [comment]
zdecode就是uncompress，加密在lflflf_ext_fopen里面

我写了个解密脚本，非常简单
```Python
# coding:utf-8
import zlib
from struct import unpack

fp = open('test2.php', 'rb')

if __name__ == '__main__':
    ret = fp.read(25)
    if ret != '\tCopyrightwww.131313.net\t':
        exit('Bad File')
    ulen = unpack('<Q', fp.read(8))[0]
    flen = unpack('<Q', fp.read(8))[0]
    data = fp.read(flen)
    result = ''
    for i in range(flen):
        result += chr((ord(data[i]) - 7 - i) % 256)
    print(zlib.decompress(result))

```
