### ISSUE TITLE
不能用python3！！！！！！！！！！！

### ISSUE THREAD

**Issue by k0njacccc** [Skactor/php_screw-decrypt#2]
不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！不能用python3！！！！！！！！！！！

**Comment by Slzdude** [comment]
已修复
