### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by gvsurenderreddy** [Skactor/php_screw-decrypt#3]
Hello sir 
How can i use your software to decrypt a php screw file .Kindly help thanks sir

**Comment by Slzdude** [comment]
just put the encrypted php file in the project dir and run the decode_screw.py with python

or you can show me the file

Developers may modify the screw algorithm. At this time, they may need to reverse engineer the corresponding dynamic link library to know how to decrypt.

**Comment by gvsurenderreddy** [comment]
Hello sir it does't work for me

**Comment by gvsurenderreddy** [comment]
i have uploaded the file here if you can have a look please let me know https://www94.zippyshare.com/v/lM0KFbXU/file.html

**Comment by Slzdude** [comment]
just test with this new script: [php_screw-decrypt.zip](https://github.com/Skactor/php_screw-decrypt/files/5177455/php_screw-decrypt.zip)

**Comment by gvsurenderreddy** [comment]
Sir thanks for your reply and Help I see the zip has backup index.php.bak its same as original file are these files decrypted sir .PHP version is 5.1.6 for these Phpscrew (Sorry I was seeing .bak file i must see .php)

**Comment by gvsurenderreddy** [comment]
Your great sir you have made my Day thank you so much honestly I owe u a beer Cheers
